name: Info 

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print run attempt
        run: |
          echo "Run attempt: ${{ github.run_attempt }}"

      - name: Print event object
        env:
          EVENT: ${{ toJSON(github.event) }}
        run: echo "$EVENT"
